apps/cart/urls.py
from django.urls import re_path
from .views import CartAddView, CartInfoView, CartUpdateView, CartDeleteView

app_name = 'cart'
urlpatterns = [
    re_path('^add/$', CartAddView.as_view(), name='add'),  # 添加购物车
    re_path('^$', CartInfoView.as_view(), name='show'),  # 购物车页面
    re_path('^update', CartUpdateView.as_view(), name='update'),  # 更新购物车记录
    re_path('^delete', CartDeleteView.as_view(), name='delete'),  # 删除购物车记录

]

apps/goods/urls.py
from django.urls import re_path
from apps.goods.views import IndexView, DetailView, ListView

app_name = 'goods'
urlpatterns = [
    re_path(r'^index/$', IndexView.as_view(), name='index'),  # 首页
    re_path(r'^goods/(?P<goods_id>\d+)$', DetailView.as_view(), name='detail'),  # 商品详情页
    re_path(r'^list/(?P<type_id>\d+)/(?P<page>\d+)$', ListView.as_view(), name='list'),  # 商品列表页
]

apps/order/urls.py
from django.urls import re_path
from .views import OrderPlaceView, OrderCommitView

app_name = 'order'
urlpatterns = [
    re_path(r'^place$', OrderPlaceView.as_view(), name='place'),  # 订单页面显示
    re_path(r'^commit$', OrderCommitView.as_view(), name='commit'),  # 订单页面显示
]

apps/user/urls.py
from django.urls import re_path
from django.contrib.auth.decorators import login_required
from apps.user.views import RegisterView, ActiveView, LoginView, UserInfoView, UserOrderView, UserAddressView, LogoutView

app_name = 'user'
urlpatterns = [
    re_path(r'^register$', RegisterView.as_view(), name='register'),  # 注册
    re_path(r'^active/(?P<token>.*)$', ActiveView.as_view(), name='active'),  # 用户激活
    re_path(r'^login$', LoginView.as_view(), name='login'),  # 用户登录
    re_path(r'^logout$', LogoutView.as_view(), name='logout'),  # 用户退出

    # re_path(r'^$', login_required(UserInfoView.as_view()), name='user'),  # 用户中心-信息页
    # re_path(r'^order$', login_required(UserOrderView.as_view()), name='order'),  # 用户中心-订单页
    # re_path(r'^address$', login_required(UserAddressView.as_view()), name='address'),  # 用户中心-地址页

    re_path(r'^$', UserInfoView.as_view(), name='user'),  # 用户中心-信息页
    re_path(r'^order/(?P<page>\d+)$', UserOrderView.as_view(), name='order'),  # 用户中心-订单页
    re_path(r'^address$', UserAddressView.as_view(), name='address'),  # 用户中心-地址页
]

dailyfresh/urls.py
from django.contrib import admin
from django.urls import path, re_path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    re_path(r'tinymce/', include('tinymce.urls')),  # 富文本编辑器
    re_path(r'search/', include('haystack.urls')),  # 全文检索
    re_path(r'^user/', include('apps.user.urls', namespace='user')),  # 用户模块
    re_path(r'^cart/', include('apps.cart.urls', namespace='cart')),  # 购物车模块
    re_path(r'^order/', include('apps.order.urls', namespace='order')),  # 订单模块
    re_path(r'^', include('apps.goods.urls', namespace='goods')),  # 商品模块
]

apps/cart/models.py
from django.db import models

# Create your models here.

apps/cart/views.py
from django.shortcuts import render
from django.views.generic import View
from django.http import JsonResponse
from apps.goods.models import GoodsSKU
from django_redis import get_redis_connection
from utils.mixin import LoginRequiredMixin
from django_redis import get_redis_connection


# Ajax
# /cart/add
class CartAddView(View):
    """ 购物车记录添加 """
    def post(self, request):
        """ 购物车记录添加"""
        user = request.user
        if not user.is_authenticated:
            # 用户未登录
            return JsonResponse({'res': 0, 'errmsg': '请先登录'})

        # 数据接收
        sku_id = request.POST.get('sku_id')
        count = request.POST.get('count')

        # 数据校验

        # 校验数据完整性
        if not all([sku_id, count]):
            return JsonResponse({'res': 1, 'errmsg': '数据不完整'})

        # 校验商品数量
        try:
            count = int(count)
        except Exception as e:
            return JsonResponse({'res': 2, 'errmsg': '商品数目出错'})

        # 校验商品是否存在
        try:
            sku = GoodsSKU.objects.get(id=sku_id)
        except GoodsSKU.DoesNotExist:
            return JsonResponse({'res': 3, 'errmsg': '商品不存在'})

        # 业务处理：添加购物车记录
        con = get_redis_connection('default')
        cart_key = 'cart_%d' % user.id
        # 查找redis数据库中是否已经有该记录
        # 已存在则更新，不存在就添加
        cart_count = con.hget(cart_key, sku_id)
        if cart_count:
            # 已存在，累加购物车商品的数目
            count += int(cart_count)

        # 校验商品的库存
        if count > sku.stock:
            return JsonResponse({'res': 4, 'errmsg': '商品库存不足'})

        # 设置redis-hash中对应的值
        # 如果sku_id已存在，则更新；没有，则添加
        con.hset(cart_key, sku_id, count)

        # 获取用户购物车商品的条目数
        total_count = con.hlen(cart_key)

        # 返回应答
        return JsonResponse({'res': 5, 'total_count': total_count, 'errmsg': '添加成功'})


# /cart
class CartInfoView(LoginRequiredMixin, View):
    """ 购物车页面 """
    def get(self, request):
        """ 购物车页面显示 """
        user = request.user
        # 获取购物车商品信息
        con = get_redis_connection('default')
        cart_key = 'cart_%d' % user.id

        # 获取用户所有的购物车信息
        # cart_key:{sku_id1:count, sku_id2:count, ...}
        cart_dict = con.hgetall(cart_key)

        # 遍历key、value获取信息
        sku_list = []
        total_price = 0
        total_count = 0
        for sku_id, count in cart_dict.items():
            sku = GoodsSKU.objects.get(id=sku_id)  # 商品sku
            sku.count = int(count)  # 商品数量
            sku.amount = sku.price * int(count)  # 商品小计
            sku_list.append(sku)
            total_price += sku.amount  # 商品合计
            total_count += int(count)  # 商品件数

        context = {
            'sku_list': sku_list,
            'total_price': total_price,
            'total_count': total_count
        }

        return render(request, 'cart.html', context)


# Ajax
# /cart/update
class CartUpdateView(View):
    """ 购物车记录更新 """
    def post(self, request):
        user = request.user
        if not user.is_authenticated:
            # 用户未登录
            return JsonResponse({'res': 0, 'errmsg': '请先登录'})

        # 数据接收
        sku_id = request.POST.get('sku_id')
        count = request.POST.get('count')

        # 数据校验

        # 校验数据完整性
        if not all([sku_id, count]):
            return JsonResponse({'res': 1, 'errmsg': '数据不完整'})

        # 校验商品数量
        try:
            count = int(count)
        except Exception as e:
            return JsonResponse({'res': 2, 'errmsg': '商品数目出错'})

        # 校验商品是否存在
        try:
            sku = GoodsSKU.objects.get(id=sku_id)
        except GoodsSKU.DoesNotExist:
            return JsonResponse({'res': 3, 'errmsg': '商品不存在'})

        # 业务处理：更新购物车记录
        con = get_redis_connection('default')
        cart_key = 'cart_%d' % user.id

        # 校验商品的库存
        if count > sku.stock:
            return JsonResponse({'res': 4, 'errmsg': '商品库存不足'})

        # 更新redis-hash中对应的值
        con.hset(cart_key, sku_id, count)

        # 获取总件数
        total_count = 0
        counts = con.hvals(cart_key)  # 获取所有的值(count)
        for count in counts:
            total_count += int(count)

        # 返回应答
        return JsonResponse({'res': 5, 'total_count': total_count, 'errmsg': '添加成功'})


# Ajax
# /cart/delete
class CartDeleteView(View):
    """ 删除购物车记录 """
    def post(self, request):
        """ 删除购物车记录 """
        user = request.user
        if not user.is_authenticated:
            # 用户未登录
            return JsonResponse({'res': 0, 'errmsg': '请先登录'})

        # 数据接收
        sku_id = request.POST.get('sku_id')

        # 数据校验

        # 校验数据完整性
        if not sku_id:
            return JsonResponse({'res': 1, 'errmsg': '商品id无效'})

        # 校验商品是否存在
        try:
            sku = GoodsSKU.objects.get(id=sku_id)
        except GoodsSKU.DoesNotExist:
            return JsonResponse({'res': 2, 'errmsg': '商品不存在'})

        # 业务处理：删除购物车记录
        con = get_redis_connection('default')
        cart_key = 'cart_%d' % user.id

        con.hdel(cart_key, sku_id)  # 删除

        # 获取总件数
        total_count = 0
        counts = con.hvals(cart_key)  # 获取所有的值(count)
        for count in counts:
            total_count += int(count)

        # 返回应答
        return JsonResponse({'res': 3, 'total_count': total_count, 'errmsg': '删除成功'})

templates/base.html
{# 登录、注册、首页 #}
{% load static %}
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
<head>
	<meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
	<title>{% block title %} {% endblock title %}</title>
	<link rel="stylesheet" type="text/css" href={% static "css/reset.css" %}>
	<link rel="stylesheet" type="text/css" href={% static "css/main.css" %}>
    {# 网页顶部js引入文件 #}
	{% block topfiles %}{% endblock topfiles %}
</head>
<body>
{# 顶部欢迎信息 #}
{% block header_con %}
	<div class="header_con">
		<div class="header">
			<div class="welcome fl">欢迎来到天天生鲜!</div>
			<div class="fr">
				{% if user.is_authenticated %}
				<div class="login_btn fl">
					欢迎您：<em>{{ user.username }}</em>
                    <span>|</span>
                    <a href="{% url 'user:logout' %}">退出</a>
				</div>
				{% else %}
				<div class="login_btn fl">
					<a href="{% url 'user:login' %}">登录</a>
					<span>|</span>
					<a href="{% url 'user:register' %}">注册</a>
				</div>
                {% endif %}
				<div class="user_link fl">
					<span>|</span>
					<a href="{% url 'user:user' %}">用户中心</a>
					<span>|</span>
					<a href="{% url 'cart:show' %}">我的购物车</a>
					<span>|</span>
					<a href="{% url 'user:order' 1 %}">我的订单</a>
				</div>
			</div>
		</div>		
	</div>
{% endblock header_con %}

{# 搜索 #}
{% block search_bar %}
	<div class="search_bar clearfix">
		<a href="{% url 'goods:index' %}" class="logo fl"><img src={% static "images/logo.png" %}></a>
        <form action="/search">
        <div class="search_con fl">
			<input type="text" class="input_text fl" name="q" placeholder="搜索商品">
			<input type="submit" class="input_btn fr" name="" value="搜索">
		</div>
        </form>
		<div class="guest_cart fr">
			<a href="{% url 'cart:show' %}" class="cart_name fl">我的购物车</a>
			<div class="goods_count fl" id="show_count">{{ cart_count }}</div>
		</div>
	</div>
{% endblock search_bar %}

    {# 内容主体 #}
	{% block body %}{% endblock body %}

    <div>{{ err_msg }}</div>

	<div class="footer">
		<div class="foot_link">
			<a href="#">关于我们</a>
			<span>|</span>
			<a href="#">联系我们</a>
			<span>|</span>
			<a href="#">招聘人才</a>
			<span>|</span>
			<a href="#">友情链接</a>		
		</div>
		<p>CopyRight © 2016 北京天天生鲜信息技术有限公司 All Rights Reserved</p>
		<p>电话：010-****888    京ICP备*******8号</p>
	</div>

    {# 底部html元素 #}
    {% block bottom %}{% endblock bottom %}

    {# 底部引入文件 #}
    {% block bottomfiles %}{% endblock bottomfiles %}

</body>
</html>

templates/base_detail_list.html
{# 详情页、列表页 #}
{% extends 'base.html' %}
{% block body %}
	<div class="navbar_con">
		<div class="navbar clearfix">
			<div class="subnav_con fl">
				<h1>全部商品分类</h1>
				<span></span>
				<ul class="subnav">
                    {% for type in types %}
                    <li><a href="{% url 'goods:list' type.id 1 %}?sort=default" class="{{ type.logo }}">{{ type.name }}</a></li>
                    {% endfor %}
				</ul>
			</div>
			<ul class="navlist fl">
				<li><a href="">首页</a></li>
				<li class="interval">|</li>
				<li><a href="">手机生鲜</a></li>
				<li class="interval">|</li>
				<li><a href="">抽奖</a></li>
			</ul>
		</div>
	</div>

    {# 详情、列表主体内容 #}
    {% block main_content %}{% endblock main_content %}

{% endblock %}

templates/base_user_center.html
{# 用户中心的3个页面 #}
{% extends 'base_no_cart.html' %}
{% block title %}天天生鲜-用户中心{% endblock title %}
{% block page_title %}用户中心{% endblock page_title %}
{% block body %}
    <div class="main_con clearfix">
        <div class="left_menu_con clearfix">
            <h3>用户中心</h3>
            <ul>
                <li><a href="{% url 'user:user' %}" {% if current_page == 'info' %}class="active"{% endif %}>· 个人信息</a></li>
                <li><a href="{% url 'user:order' 1 %}" {% if current_page == 'order' %}class="active"{% endif %}>· 全部订单</a></li>
                <li><a href="{% url 'user:address' %}" {% if current_page == 'address' %}class="active"{% endif %}>· 收货地址</a></li>
            </ul>
        </div>
    {% block right_content %}{% endblock right_content %}
    </div>
{% endblock body %}

templates/cart.html
{% extends 'base_no_cart.html' %}
{% load static %}
{% block title %}天天生鲜-购物车{% endblock %}
{% block page_title %}购物车{% endblock %}
{% block body %}
	<div class="total_count">全部商品<em>{{ total_count }}</em>件</div>
	<ul class="cart_list_th clearfix">
		<li class="col01">商品名称</li>
		<li class="col02">商品单位</li>
		<li class="col03">商品价格</li>
		<li class="col04">数量</li>
		<li class="col05">小计</li>
		<li class="col06">操作</li>
	</ul>
    <form method="post" action="{% url 'order:place' %}">
    {% csrf_token %}
    {% for sku in sku_list %}
    <ul class="cart_list_td clearfix">
		<li class="col01"><input type="checkbox" name="sku_ids" value="{{ sku.id }}" checked></li>
		<li class="col02"><img src="{{ sku.image.url }}"></li>
		<li class="col03">奇异果<br><em>{{ sku.price }}元/{{ sku.unite }}</em></li>
		<li class="col04">{{ sku.unite }}</li>
		<li class="col05">{{ sku.price }}元</li>
		<li class="col06">
			<div class="num_add">
				<a href="javascript:;" class="add fl">+</a>
				<input type="text" sku_id='{{ sku.id }}' class="num_show fl" value="{{ sku.count }}">
				<a href="javascript:;" class="minus fl">-</a>
			</div>
		</li>
		<li class="col07">{{ sku.amount }}元</li>
		<li class="col08"><a href="javascript:;">删除</a></li>
	</ul>
    {% endfor %}

	<ul class="settlements">
		<li class="col01"><input type="checkbox" name="" checked=""></li>
		<li class="col02">全选</li>
		<li class="col03">合计(不含运费)：<span>¥</span><em>{{ total_price }}</em><br>共计<b>{{ total_count }}</b>件商品</li>
		<li class="col04"><input type="submit" value="去结算"></li>
	</ul>
    </form>
{% endblock %}

{% block bottomfiles %}
    <script type="text/javascript" src={% static 'js/jquery-1.12.4.min.js' %}></script>
    <script type="text/javascript">

        // 更新页面数目、合计信息
        function update_page_info () {
            total_price = 0  // 商品合计
            total_count = 0  // 商品数目

            $('.cart_list_td').find(':checked').parents('ul').each(function () {
                total_count += parseInt($(this).find('.num_show').val())
                total_price += parseFloat($(this).children('.col07').text())
            })

            // 设置商品总数、合计
            $('.settlements').find('em').text(total_price.toFixed(2))
            $('.settlements').find('b').text(total_count)
        }


        // 全选和全不选
        $('.settlements').find(':checkbox').change(function () {
            is_checked = $(this).prop('checked')  // 获取全选框的状态
            $('.cart_list_td').find(':checkbox').each(function () {
                $(this).prop('checked', is_checked)  // 所有商品根据全选框的状态，进行全选和全不选
            })
            update_page_info()
        })


        // 商品的选中和取消选中
        $('.cart_list_td').find(':checkbox').change(function () {
            // 对应修改【全选】复选框的选择状态
            total_count = $('.cart_list_td').find(':checkbox').length  // 商品总数目
            current_count = $('.cart_list_td').find(':checked').length  // 已选商品数目
            is_checked = true
            if (current_count < total_count) {
                // 已选商品数量 小于 商品总数目，状态设为未选中
                is_checked = false
            }
            $('.settlements').find(':checkbox').prop('checked', is_checked)  // 设置【全选】的选中状态

            // 更新页面信息
            update_page_info()
        })


        // 更新购物车记录
        error_update = false
        total_count = 0
        function update_cart_info (sku_id, count) {
            csrf = $('input[name=csrfmiddlewaretoken]').val()
            // 组织参数
            params = {'sku_id': sku_id, 'count': count, 'csrfmiddlewaretoken': csrf}

            // 设置Ajax请求为同步
            $.ajaxSettings.async = false
            $.post('/cart/update', params, function (data) {
                if (data.res == 5){
                    error_update = false  // 更新成功
                    total_count = data.total_count
                } else {
                    error_update = true  // 更新失败
                    alert(data.errmsg)
                }
            })
            // 设置Ajax请求为异步
            $.ajaxSettings.async = true  // 因为是全局，所以这里需要重新设置成异步
        }


        // 购物车中商品的增加
        $('.add').click(function () {
            // 获取对应商品的sku_id、count
            sku_id = $(this).next().attr('sku_id')
            count = $(this).next().val()
            count = parseInt(count) + 1

            // 更新记录
            update_cart_info(sku_id, count)

            if (error_update == false){
                // 更新成功后
                // 更新商品的数量
                $(this).next().val(count)

                // 更新商品的小计
                price = $(this).parents('.cart_list_td').find('.col05').text()
                amount = parseFloat(price) * count
                $(this).parents('.cart_list_td').find('.col07').text(amount.toFixed(2)+'元')

                // 如果当前商品被选中，则刷新商品总数目和合计
                is_checked = $(this).parents('.cart_list_td').find(':checkbox').prop('checked')
                if (is_checked){
                    update_page_info()
                }

                // 更新上方 【全部商品】总件数
                $('.total_count').find('em').text(total_count)
            }
        })

        // 购物车中商品的减少
        $('.minus').click(function () {
            // 获取对应商品的sku_id、count
            sku_id = $(this).prev().attr('sku_id')
            count = $(this).prev().val()

            if (parseInt(count) <=1 )
                return
            count = parseInt(count) - 1

            // 更新记录
            update_cart_info(sku_id, count)

            if (error_update == false){
                // 更新成功后
                // 更新商品的数量
                $(this).prev().val(count)

                // 更新商品的小计
                price = $(this).parents('.cart_list_td').find('.col05').text()
                amount = parseFloat(price) * count
                $(this).parents('.cart_list_td').find('.col07').text(amount.toFixed(2)+'元')

                // 如果当前商品被选中，则刷新商品总数目和合计
                is_checked = $(this).parents('.cart_list_td').find(':checkbox').prop('checked')
                if (is_checked){
                    update_page_info()
                }

                // 更新上方 【全部商品】总件数
                $('.total_count').find('em').text(total_count)
            }
        })

        // 手动输入购物车中商品的数量
        pre_count = 0
        $('.num_show').focus(function () {
            pre_count = $(this).val()  // 记录输入前的数量
        })

        $('.num_show').blur(function () {
            // 获取对应商品的sku_id、count
            sku_id = $(this).attr('sku_id')
            count = $(this).val()

            //数据校验
            if (isNaN(count) || count.trim().length==0 || parseInt(parseFloat(count)) <=0){
                // 如果输入的非数字、空格、负数
                $(this).val(pre_count)  // 设置商品数量为用户输入之前的值
                return
            }

            // 更新记录
            count = parseInt(count)
            update_cart_info(sku_id, count)

            if (error_update == false){
                // 更新成功后
                // 更新商品的数量
                $(this).val(count)

                // 更新商品的小计
                price = $(this).parents('.cart_list_td').find('.col05').text()
                amount = parseFloat(price) * count
                $(this).parents('.cart_list_td').find('.col07').text(amount.toFixed(2)+'元')

                // 如果当前商品被选中，则刷新商品总数目和合计
                is_checked = $(this).parents('.cart_list_td').find(':checkbox').prop('checked')
                if (is_checked){
                    update_page_info()
                }

                // 更新上方 【全部商品】总件数
                $('.total_count').find('em').text(total_count)
            } else {
                // 设置商品数量为用户输入之前的值
                $(this).val(pre_count)
            }
        })


        // 删除购物车中的记录
        $('.cart_list_td').children('.col08').children('a').click(function () {
            // 获取对应商品的sku_id
            sku_id = $(this).parents('ul').find('.num_show').attr('sku_id')
            csrf = $('input[name=csrfmiddlewaretoken]').val()
            // 组织参数
            params = {'sku_id': sku_id, 'csrfmiddlewaretoken': csrf}

            // 获取商品所在的ul
            sku_ul = $(this).parents('ul')

            // 发送请求
            $.post('/cart/delete', params, function (data) {
                if (data.res == 3){
                    // 删除成功
                    sku_ul.remove()  // 移除商品所在ul

                    // 获取商品是否被选中
                    is_checked = sku_ul.find(':checkbox').prop('checked')
                    if (is_checked){
                        update_page_info()
                    }

                    // 更新上方 【全部商品】总件数
                    $('.total_count').find('em').text(data.total_count)

                } else {
                    // 删除失败
                    alert(data.errmsg)
                }
            })

        })

    </script>
{% endblock %}

templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block title %}天天生鲜-首页{% endblock title %}
{% block topfiles %}
    <script type="text/javascript" src={% static "js/jquery-1.12.4.min.js" %}></script>
	<script type="text/javascript" src={% static "js/jquery-ui.min.js" %}></script>
	<script type="text/javascript" src={% static "js/slide.js" %}></script>
{% endblock topfiles %}

{% block body %}
	<div class="navbar_con">
		<div class="navbar">
			<h1 class="fl">全部商品分类</h1>
			<ul class="navlist fl">
				<li><a href="">首页</a></li>
				<li class="interval">|</li>
				<li><a href="">手机生鲜</a></li>
				<li class="interval">|</li>
				<li><a href="">抽奖</a></li>
			</ul>
		</div>
	</div>

	<div class="center_con clearfix">
		<ul class="subnav fl">
            {% for type in goods_type %}
            <li><a href="{% url 'goods:list' type.id 1 %}?sort=default" class="{{ type.logo }}">{{ type.name }}</a></li>
            {% endfor %}
		</ul>
		<div class="slide fl">
			<ul class="slide_pics">
                {% for goods in goods_banner %}
                <a href="{% url 'goods:detail' goods.sku.id %}"><li><img src={{ goods.image.url }} alt="幻灯片"></li></a>
                {% endfor %}
			</ul>
			<div class="prev"></div>
			<div class="next"></div>
			<ul class="points"></ul>
		</div>
		<div class="adv fl">
            {% for banner in promotion_banner %}
			<a href="{{ banner.url }}"><img src={{ banner.image.url }}></a>
            {% endfor %}
		</div>
	</div>

	{% for type in goods_type %}
    <div class="list_model">
		<div class="list_title clearfix">
			<h3 class="fl" id="model01">{{ type.name }}</h3>
			<div class="subtitle fl">
				<span>|</span>
				{% for goods in type.title_goods %}
                    <a href="{% url 'goods:detail' goods.sku.id %}">{{ goods.sku.name }}</a>
                {% endfor %}
			</div>
			<a href="#" class="goods_more fr" id="fruit_more">查看更多 ></a>
		</div>

		<div class="goods_con clearfix">
			<div class="goods_banner fl"><img src={{ type.image.url }}></div>
			<ul class="goods_list fl">
				{% for goods in type.detail_goods %}
                <li>
					<h4><a href="{% url 'goods:detail' goods.sku.id %}">{{ goods.sku.name }}</a></h4>
					<a href="{% url 'goods:detail' goods.sku.id %}"><img src={{ goods.sku.image.url }}></a>
					<div class="prize">¥ {{ goods.sku.price }}</div>
				</li>
                {% endfor %}
			</ul>
		</div>
	</div>
    {% endfor %}

{% endblock body %}



templates/list.html
{% extends 'base_detail_list.html' %}
{% block title %}天天生鲜-商品列表{% endblock %}

{% block main_content %}
	<div class="breadcrumb">
		<a href="#">全部分类</a>
		<span>></span>
		<a href="#">{{ goods_type }}</a>
	</div>

	<div class="main_wrap clearfix">
		<div class="r_wrap fr clearfix">
			<div class="sort_bar">
				<a href="{% url 'goods:list' goods_type.id 1 %}?sort=default" {% if sort == 'default' %}class="active"{% endif %}>默认</a>
				<a href="{% url 'goods:list' goods_type.id 1 %}?sort=price" {% if sort == 'price' %}class="active"{% endif %}>价格</a>
				<a href="{% url 'goods:list' goods_type.id 1 %}?sort=hot" {% if sort == 'hot' %}class="active"{% endif %}>人气</a>
			</div>

			<ul class="goods_type_list clearfix">
                {% for sku in skus_page %}
				<li>
					<a href="{% url 'goods:detail' sku.id %}"><img src="{{ sku.image.url }}"></a>
					<h4><a href="{% url 'goods:detail' sku.id %}">{{ sku.name }}</a></h4>
					<div class="operate">
						<span class="prize">￥{{ sku.price }}</span>
						<span class="unit">{{ sku.price }}/{{ sku.unite }}</span>
						<a href="#" class="add_goods" title="加入购物车"></a>
					</div>
				</li>
                {% endfor %}
			</ul>

			<div class="pagenation">
				{% if skus_page.has_previous %}
				<a href="{% url 'goods:list' goods_type.id skus_page.previous_page_number%}?sort={{ sort }}">上一页</a>
                {% endif %}
                {% for pindex in pages %}
                    {% if pindex == skus_page.number %}
                    <a href="{% url 'goods:list' goods_type.id pindex%}?sort={{ sort }}"  class="active">{{ pindex }}</a>
                    {% else %}
                    <a href="{% url 'goods:list' goods_type.id pindex%}?sort={{ sort }}">{{ pindex }}</a>
                    {% endif %}
                {% endfor %}
				{% if skus_page.has_next %}
                <a href="{% url 'goods:list' goods_type.id skus_page.next_page_number%}?sort={{ sort }}">下一页></a>
                {% endif %}
			</div>
		</div>
	</div>
{% endblock %}